install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.60.0/hugo_extended_0.60.0_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb

script:
  - git submodule update --init --recursive
  - hugo

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: false
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: source
