baseURL = "https://libreofficeid.github.io/"
title = "Komunitas LibreOffice Indonesia"
theme = "navigator-hugo"
summaryLength = 5

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Site Params
[params]
    logo = "images/logo.png"
    author = "LibreOffice ID"
    description = "LibreOffice ID merupakan komunitas LibreOffice yang bertujuan untuk mengajak para pegiat LibreOffice di Indonesia untuk turut andil berkontribusi dalam pengembangan LibreOffice."
    weight = 1
    title = "Komunitas LibreOffice Indonesia"
    dateFormat = "2 January 2006"

    home = "Home"
    menufixed = false

    footerDescription = "Komunitas LibreOffice Indonesia adalah suatu komunitas pengguna, pegiat, dan kontributor LibreOffice di Indonesia"
    footerServiceTitle = "Layanan"
    footerQuicklinkTitle = "Pranala Luar"
    footerAboutTitle = "Tentang"
    footerSocmedTitle = "Mari Bersua"

    # Hero Area Section
    [params.hero]
        enable  = true
        heading = "Komunitas LibreOffice Indonesia"
        description = "Mari aktif berkontribusi untuk LibreOffice"
        button  = true
        btnText = "Mari Bergabung"
        btnURL  = "https://t.me/LibreOfficeID"
        videoThumb = "images/slider/video-player-thumb.webp"
        videoURL   = "https://www.youtube.com/watch?v=uAhhugnH9QY"

    # About 2 Section
    [params.aboutSm]
        enable  = true
        title   = "Tentang Kami"
        description = "Komunitas LibreOffice Indonesia adalah komunitas nonprofit yang mewadahi para pengguna, pegiat, dan kontributor LibreOffice di Indonesia. Kontribusi yang dapat dilakukan antara lain menerjemahkan LibreOffice, membuat ekstensi, atau berkontribusi dalam pengembangan kualitas LibreOffice (QA). Komunitas LibreOffice bermula dari grup komunitas di Facebook dengan anggota yang sudah mencapai angka ribuan. Kini, LibreOffice ID juga menggunakan media komunikasi Telegram untuk akses yang lebih cepat dan realtime guna sekadar berdiskusi hangat, tanya jawab, dan pemecahan permasalahan terkait penggunaan dan kontribusi terhadap LibreOffice. Mari aktif berkontribusi untuk LibreOffice!"

    # Blog Section On Homepage
    [params.blog]
        enable  = true
        topTitle= ""
        title   = "Warta Terkini LibreOffice Indonesia."
        subtitle= ""

    #Feature Section
    [params.feature]
        enable  = true
        title   = "Lumbung"
        description = "memang lumbung"

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "about"
        url     = "about"
        weight  = 2
    [[menu.nav]]
        name    = "service"
        url     = "service"
        weight  = 3
    [[menu.nav]]
        name    = "portfolio"
        url     = "portfolio"
        weight  = 4
    [[menu.nav]]
        name    = "blog"
        url     = "blog"
        weight  = 5
    [[menu.nav]]
        name    = "contact"
        url     = "contact"
        weight  = 6

    # Footer Service Menu
    [[menu.service]]
        name    = ""
        url     = ""
        weight  = 1
    [[menu.service]]
        name    = ""
        url     = ""
        weight  = 2
    [[menu.service]]
        name    = ""
        url     = ""
        weight  = 3

    # Footer Quick links Menu
    [[menu.quicklink]]
        name    = ""
        url     = ""
        weight  = 1
    [[menu.quicklink]]
        name    = ""
        url     = ""
        weight  = 2

